### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by 0xced** [blakewatters/TransitionKit#28]
Could you please tag a new release with the changes introduced in #27?

Without a new tagged version, it is impossible to have a podspec that depends on TransitionKit and use the new `TKStateMachineDidChangeStateTransitionUserInfoKey`.

**Comment by 0xced** [comment]
Ping.

I am currently polluting all my Podfiles with `pod 'TransitionKit', { :git => 'https://github.com/blakewatters/TransitionKit.git', :commit => '750cc2dfd5c2ef578089ebe8424eaec7e1ebce08' } ` in the meantime. 😞

**Comment by blakewatters** [comment]
Sorry @0xced — the issue got lost in my inbox. v2.2.0 pushed to CocoaPods!
